### ISSUE TITLE
Práctica 4 Diagrama de clases

### ISSUE THREAD

**Issue by Brisa-4** [SistemasTecTlaxiaco/practica-de-diagrama-de-clases-Yabin-2021#2]
[Diagrama de clases.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-diagrama-de-clases-Yabin-2021/files/8469381/Diagrama.de.clases.pdf)

**Comment by CxrlosMX** [comment]
Excelente trabajo compañeros, calificación obtenida: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
